# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SoftKeyBoard.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SoftKeyBoard(object):

    def __init__(self):
        # 原始键盘风格
        self.style = """*{{font: 75 {0}pt;}}
#SoftKeyBoard{{background-color: rgb(153, 153, 153);}}
QPushButton{{color: rgb(255,255,255); background-color: rgb(67,63,59); border-radius: 7px;}}
QPushButton:hover{{background-color: rgb(127,122,117)}}
QPushButton:pressed{{background-color: rgb(33,30,27)}}"""

    def set_style(self, font_sz=18):
        """ 设置字体 """
        return self.style.format(font_sz)

    def setupUi(self, SoftKeyBoard):
        SoftKeyBoard.setObjectName("SoftKeyBoard")
        SoftKeyBoard.setWindowModality(QtCore.Qt.NonModal)
        SoftKeyBoard.setEnabled(True)
        SoftKeyBoard.resize(816, 447)
        SoftKeyBoard.setStyleSheet(self.set_style())
        self.gridLayout_2 = QtWidgets.QGridLayout(SoftKeyBoard)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_keyboard_ = QtWidgets.QWidget(SoftKeyBoard)
        self.widget_keyboard_.setObjectName("widget_keyboard_")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_keyboard_)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.num_1_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_1_.sizePolicy().hasHeightForWidth())
        self.num_1_.setSizePolicy(sizePolicy)
        self.num_1_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_1_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_1_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_1_.setObjectName("num_1_")
        self.horizontalLayout_2.addWidget(self.num_1_)
        self.num_2_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_2_.sizePolicy().hasHeightForWidth())
        self.num_2_.setSizePolicy(sizePolicy)
        self.num_2_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_2_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_2_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_2_.setObjectName("num_2_")
        self.horizontalLayout_2.addWidget(self.num_2_)
        self.num_3_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_3_.sizePolicy().hasHeightForWidth())
        self.num_3_.setSizePolicy(sizePolicy)
        self.num_3_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_3_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_3_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_3_.setObjectName("num_3_")
        self.horizontalLayout_2.addWidget(self.num_3_)
        self.num_4_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_4_.sizePolicy().hasHeightForWidth())
        self.num_4_.setSizePolicy(sizePolicy)
        self.num_4_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_4_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_4_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_4_.setObjectName("num_4_")
        self.horizontalLayout_2.addWidget(self.num_4_)
        self.num_5_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_5_.sizePolicy().hasHeightForWidth())
        self.num_5_.setSizePolicy(sizePolicy)
        self.num_5_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_5_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_5_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_5_.setObjectName("num_5_")
        self.horizontalLayout_2.addWidget(self.num_5_)
        self.num_6_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_6_.sizePolicy().hasHeightForWidth())
        self.num_6_.setSizePolicy(sizePolicy)
        self.num_6_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_6_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_6_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_6_.setObjectName("num_6_")
        self.horizontalLayout_2.addWidget(self.num_6_)
        self.num_7_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_7_.sizePolicy().hasHeightForWidth())
        self.num_7_.setSizePolicy(sizePolicy)
        self.num_7_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_7_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_7_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_7_.setObjectName("num_7_")
        self.horizontalLayout_2.addWidget(self.num_7_)
        self.num_8_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_8_.sizePolicy().hasHeightForWidth())
        self.num_8_.setSizePolicy(sizePolicy)
        self.num_8_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_8_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_8_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_8_.setObjectName("num_8_")
        self.horizontalLayout_2.addWidget(self.num_8_)
        self.num_9_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_9_.sizePolicy().hasHeightForWidth())
        self.num_9_.setSizePolicy(sizePolicy)
        self.num_9_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_9_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_9_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_9_.setObjectName("num_9_")
        self.horizontalLayout_2.addWidget(self.num_9_)
        self.num_0_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_0_.sizePolicy().hasHeightForWidth())
        self.num_0_.setSizePolicy(sizePolicy)
        self.num_0_.setMinimumSize(QtCore.QSize(40, 40))
        self.num_0_.setMaximumSize(QtCore.QSize(80, 80))
        self.num_0_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.num_0_.setObjectName("num_0_")
        self.horizontalLayout_2.addWidget(self.num_0_)
        self.btn_dec_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dec_.sizePolicy().hasHeightForWidth())
        self.btn_dec_.setSizePolicy(sizePolicy)
        self.btn_dec_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_dec_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_dec_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_dec_.setObjectName("btn_dec_")
        self.horizontalLayout_2.addWidget(self.btn_dec_)
        self.btn_add_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_.sizePolicy().hasHeightForWidth())
        self.btn_add_.setSizePolicy(sizePolicy)
        self.btn_add_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_add_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_add_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_add_.setObjectName("btn_add_")
        self.horizontalLayout_2.addWidget(self.btn_add_)
        self.btn_backspace_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_backspace_.sizePolicy().hasHeightForWidth())
        self.btn_backspace_.setSizePolicy(sizePolicy)
        self.btn_backspace_.setMinimumSize(QtCore.QSize(87, 40))
        self.btn_backspace_.setMaximumSize(QtCore.QSize(173, 80))
        self.btn_backspace_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_backspace_.setObjectName("btn_backspace_")
        self.horizontalLayout_2.addWidget(self.btn_backspace_)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.char_q_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_q_.sizePolicy().hasHeightForWidth())
        self.char_q_.setSizePolicy(sizePolicy)
        self.char_q_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_q_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_q_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_q_.setObjectName("char_q_")
        self.horizontalLayout.addWidget(self.char_q_)
        self.char_w_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_w_.sizePolicy().hasHeightForWidth())
        self.char_w_.setSizePolicy(sizePolicy)
        self.char_w_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_w_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_w_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_w_.setObjectName("char_w_")
        self.horizontalLayout.addWidget(self.char_w_)
        self.char_e_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_e_.sizePolicy().hasHeightForWidth())
        self.char_e_.setSizePolicy(sizePolicy)
        self.char_e_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_e_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_e_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_e_.setObjectName("char_e_")
        self.horizontalLayout.addWidget(self.char_e_)
        self.char_r_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_r_.sizePolicy().hasHeightForWidth())
        self.char_r_.setSizePolicy(sizePolicy)
        self.char_r_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_r_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_r_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_r_.setObjectName("char_r_")
        self.horizontalLayout.addWidget(self.char_r_)
        self.char_t_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_t_.sizePolicy().hasHeightForWidth())
        self.char_t_.setSizePolicy(sizePolicy)
        self.char_t_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_t_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_t_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_t_.setObjectName("char_t_")
        self.horizontalLayout.addWidget(self.char_t_)
        self.char_y_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_y_.sizePolicy().hasHeightForWidth())
        self.char_y_.setSizePolicy(sizePolicy)
        self.char_y_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_y_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_y_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_y_.setObjectName("char_y_")
        self.horizontalLayout.addWidget(self.char_y_)
        self.char_u_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_u_.sizePolicy().hasHeightForWidth())
        self.char_u_.setSizePolicy(sizePolicy)
        self.char_u_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_u_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_u_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_u_.setObjectName("char_u_")
        self.horizontalLayout.addWidget(self.char_u_)
        self.char_i_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_i_.sizePolicy().hasHeightForWidth())
        self.char_i_.setSizePolicy(sizePolicy)
        self.char_i_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_i_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_i_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_i_.setObjectName("char_i_")
        self.horizontalLayout.addWidget(self.char_i_)
        self.char_o_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_o_.sizePolicy().hasHeightForWidth())
        self.char_o_.setSizePolicy(sizePolicy)
        self.char_o_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_o_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_o_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_o_.setObjectName("char_o_")
        self.horizontalLayout.addWidget(self.char_o_)
        self.char_p_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_p_.sizePolicy().hasHeightForWidth())
        self.char_p_.setSizePolicy(sizePolicy)
        self.char_p_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_p_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_p_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_p_.setObjectName("char_p_")
        self.horizontalLayout.addWidget(self.char_p_)
        self.btn_left_bracket_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_left_bracket_.sizePolicy().hasHeightForWidth())
        self.btn_left_bracket_.setSizePolicy(sizePolicy)
        self.btn_left_bracket_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_left_bracket_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_left_bracket_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_left_bracket_.setObjectName("btn_left_bracket_")
        self.horizontalLayout.addWidget(self.btn_left_bracket_)
        self.btn_right_bracket_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_right_bracket_.sizePolicy().hasHeightForWidth())
        self.btn_right_bracket_.setSizePolicy(sizePolicy)
        self.btn_right_bracket_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_right_bracket_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_right_bracket_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_right_bracket_.setObjectName("btn_right_bracket_")
        self.horizontalLayout.addWidget(self.btn_right_bracket_)
        self.btn_slash_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_slash_.sizePolicy().hasHeightForWidth())
        self.btn_slash_.setSizePolicy(sizePolicy)
        self.btn_slash_.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_slash_.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_slash_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_slash_.setObjectName("btn_slash_")
        self.horizontalLayout.addWidget(self.btn_slash_)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.char_a_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_a_.sizePolicy().hasHeightForWidth())
        self.char_a_.setSizePolicy(sizePolicy)
        self.char_a_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_a_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_a_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_a_.setObjectName("char_a_")
        self.horizontalLayout_3.addWidget(self.char_a_)
        self.char_s_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_s_.sizePolicy().hasHeightForWidth())
        self.char_s_.setSizePolicy(sizePolicy)
        self.char_s_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_s_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_s_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_s_.setObjectName("char_s_")
        self.horizontalLayout_3.addWidget(self.char_s_)
        self.char_d_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_d_.sizePolicy().hasHeightForWidth())
        self.char_d_.setSizePolicy(sizePolicy)
        self.char_d_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_d_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_d_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_d_.setObjectName("char_d_")
        self.horizontalLayout_3.addWidget(self.char_d_)
        self.char_f_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_f_.sizePolicy().hasHeightForWidth())
        self.char_f_.setSizePolicy(sizePolicy)
        self.char_f_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_f_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_f_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_f_.setObjectName("char_f_")
        self.horizontalLayout_3.addWidget(self.char_f_)
        self.char_g_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_g_.sizePolicy().hasHeightForWidth())
        self.char_g_.setSizePolicy(sizePolicy)
        self.char_g_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_g_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_g_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_g_.setObjectName("char_g_")
        self.horizontalLayout_3.addWidget(self.char_g_)
        self.char_h_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_h_.sizePolicy().hasHeightForWidth())
        self.char_h_.setSizePolicy(sizePolicy)
        self.char_h_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_h_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_h_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_h_.setObjectName("char_h_")
        self.horizontalLayout_3.addWidget(self.char_h_)
        self.char_j_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_j_.sizePolicy().hasHeightForWidth())
        self.char_j_.setSizePolicy(sizePolicy)
        self.char_j_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_j_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_j_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_j_.setObjectName("char_j_")
        self.horizontalLayout_3.addWidget(self.char_j_)
        self.char_k_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_k_.sizePolicy().hasHeightForWidth())
        self.char_k_.setSizePolicy(sizePolicy)
        self.char_k_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_k_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_k_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_k_.setObjectName("char_k_")
        self.horizontalLayout_3.addWidget(self.char_k_)
        self.char_l_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_l_.sizePolicy().hasHeightForWidth())
        self.char_l_.setSizePolicy(sizePolicy)
        self.char_l_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_l_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_l_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_l_.setObjectName("char_l_")
        self.horizontalLayout_3.addWidget(self.char_l_)
        self.btn_semicolon_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_semicolon_.sizePolicy().hasHeightForWidth())
        self.btn_semicolon_.setSizePolicy(sizePolicy)
        self.btn_semicolon_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_semicolon_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_semicolon_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_semicolon_.setObjectName("btn_semicolon_")
        self.horizontalLayout_3.addWidget(self.btn_semicolon_)
        self.btn_quota_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_quota_.sizePolicy().hasHeightForWidth())
        self.btn_quota_.setSizePolicy(sizePolicy)
        self.btn_quota_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_quota_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_quota_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_quota_.setObjectName("btn_quota_")
        self.horizontalLayout_3.addWidget(self.btn_quota_)
        self.btn_enter_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_enter_.sizePolicy().hasHeightForWidth())
        self.btn_enter_.setSizePolicy(sizePolicy)
        self.btn_enter_.setMinimumSize(QtCore.QSize(92, 40))
        self.btn_enter_.setMaximumSize(QtCore.QSize(185, 80))
        self.btn_enter_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_enter_.setObjectName("btn_enter_")
        self.horizontalLayout_3.addWidget(self.btn_enter_)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.char_z_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_z_.sizePolicy().hasHeightForWidth())
        self.char_z_.setSizePolicy(sizePolicy)
        self.char_z_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_z_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_z_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_z_.setObjectName("char_z_")
        self.horizontalLayout_4.addWidget(self.char_z_)
        self.char_x_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_x_.sizePolicy().hasHeightForWidth())
        self.char_x_.setSizePolicy(sizePolicy)
        self.char_x_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_x_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_x_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_x_.setObjectName("char_x_")
        self.horizontalLayout_4.addWidget(self.char_x_)
        self.char_c_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_c_.sizePolicy().hasHeightForWidth())
        self.char_c_.setSizePolicy(sizePolicy)
        self.char_c_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_c_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_c_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_c_.setObjectName("char_c_")
        self.horizontalLayout_4.addWidget(self.char_c_)
        self.char_v_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_v_.sizePolicy().hasHeightForWidth())
        self.char_v_.setSizePolicy(sizePolicy)
        self.char_v_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_v_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_v_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_v_.setObjectName("char_v_")
        self.horizontalLayout_4.addWidget(self.char_v_)
        self.char_b_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_b_.sizePolicy().hasHeightForWidth())
        self.char_b_.setSizePolicy(sizePolicy)
        self.char_b_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_b_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_b_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_b_.setObjectName("char_b_")
        self.horizontalLayout_4.addWidget(self.char_b_)
        self.char_n_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_n_.sizePolicy().hasHeightForWidth())
        self.char_n_.setSizePolicy(sizePolicy)
        self.char_n_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_n_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_n_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_n_.setObjectName("char_n_")
        self.horizontalLayout_4.addWidget(self.char_n_)
        self.char_m_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.char_m_.sizePolicy().hasHeightForWidth())
        self.char_m_.setSizePolicy(sizePolicy)
        self.char_m_.setMinimumSize(QtCore.QSize(40, 40))
        self.char_m_.setMaximumSize(QtCore.QSize(80, 80))
        self.char_m_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.char_m_.setObjectName("char_m_")
        self.horizontalLayout_4.addWidget(self.char_m_)
        self.btn_comma_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_comma_.sizePolicy().hasHeightForWidth())
        self.btn_comma_.setSizePolicy(sizePolicy)
        self.btn_comma_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_comma_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_comma_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_comma_.setObjectName("btn_comma_")
        self.horizontalLayout_4.addWidget(self.btn_comma_)
        self.btn_dot_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dot_.sizePolicy().hasHeightForWidth())
        self.btn_dot_.setSizePolicy(sizePolicy)
        self.btn_dot_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_dot_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_dot_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_dot_.setObjectName("btn_dot_")
        self.horizontalLayout_4.addWidget(self.btn_dot_)
        self.btn_backslash_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_backslash_.sizePolicy().hasHeightForWidth())
        self.btn_backslash_.setSizePolicy(sizePolicy)
        self.btn_backslash_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_backslash_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_backslash_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_backslash_.setObjectName("btn_backslash_")
        self.horizontalLayout_4.addWidget(self.btn_backslash_)
        self.btn_up_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_up_.sizePolicy().hasHeightForWidth())
        self.btn_up_.setSizePolicy(sizePolicy)
        self.btn_up_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_up_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_up_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_up_.setObjectName("btn_up_")
        self.horizontalLayout_4.addWidget(self.btn_up_)
        self.btn_shift_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_shift_.sizePolicy().hasHeightForWidth())
        self.btn_shift_.setSizePolicy(sizePolicy)
        self.btn_shift_.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_shift_.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_shift_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_shift_.setObjectName("btn_shift_")
        self.horizontalLayout_4.addWidget(self.btn_shift_)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_clear_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_.sizePolicy().hasHeightForWidth())
        self.btn_clear_.setSizePolicy(sizePolicy)
        self.btn_clear_.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_clear_.setMaximumSize(QtCore.QSize(200, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_clear_.setFont(font)
        self.btn_clear_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_clear_.setObjectName("btn_clear_")
        self.horizontalLayout_5.addWidget(self.btn_clear_)
        self.btn_space_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_space_.sizePolicy().hasHeightForWidth())
        self.btn_space_.setSizePolicy(sizePolicy)
        self.btn_space_.setMinimumSize(QtCore.QSize(290, 40))
        self.btn_space_.setMaximumSize(QtCore.QSize(580, 80))
        self.btn_space_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_space_.setText("")
        self.btn_space_.setObjectName("btn_space_")
        self.horizontalLayout_5.addWidget(self.btn_space_)
        self.btn_capslock_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_capslock_.sizePolicy().hasHeightForWidth())
        self.btn_capslock_.setSizePolicy(sizePolicy)
        self.btn_capslock_.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_capslock_.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_capslock_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_capslock_.setCheckable(True)
        self.btn_capslock_.setObjectName("btn_capslock_")
        self.horizontalLayout_5.addWidget(self.btn_capslock_)
        self.btn_left_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_left_.sizePolicy().hasHeightForWidth())
        self.btn_left_.setSizePolicy(sizePolicy)
        self.btn_left_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_left_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_left_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_left_.setObjectName("btn_left_")
        self.horizontalLayout_5.addWidget(self.btn_left_)
        self.btn_down_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_down_.sizePolicy().hasHeightForWidth())
        self.btn_down_.setSizePolicy(sizePolicy)
        self.btn_down_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_down_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_down_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_down_.setObjectName("btn_down_")
        self.horizontalLayout_5.addWidget(self.btn_down_)
        self.btn_right_ = QtWidgets.QPushButton(self.widget_keyboard_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_right_.sizePolicy().hasHeightForWidth())
        self.btn_right_.setSizePolicy(sizePolicy)
        self.btn_right_.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_right_.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_right_.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_right_.setObjectName("btn_right_")
        self.horizontalLayout_5.addWidget(self.btn_right_)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_keyboard_, 0, 0, 1, 1)

        self.retranslateUi(SoftKeyBoard)
        QtCore.QMetaObject.connectSlotsByName(SoftKeyBoard)

    def retranslateUi(self, SoftKeyBoard):
        _translate = QtCore.QCoreApplication.translate
        SoftKeyBoard.setWindowTitle(_translate("SoftKeyBoard", "Input Panel"))
        self.num_1_.setText(_translate("SoftKeyBoard", "!\n"
"1"))
        self.num_2_.setText(_translate("SoftKeyBoard", "@\n"
"2"))
        self.num_3_.setText(_translate("SoftKeyBoard", "#\n"
"3"))
        self.num_4_.setText(_translate("SoftKeyBoard", "$\n"
"4"))
        self.num_5_.setText(_translate("SoftKeyBoard", "%\n"
"5"))
        self.num_6_.setText(_translate("SoftKeyBoard", "^\n"
"6"))
        self.num_7_.setText(_translate("SoftKeyBoard", "&&\n"
"7"))
        self.num_8_.setText(_translate("SoftKeyBoard", "*\n"
"8"))
        self.num_9_.setText(_translate("SoftKeyBoard", "(\n"
"9"))
        self.num_0_.setText(_translate("SoftKeyBoard", ")\n"
"0"))
        self.btn_dec_.setText(_translate("SoftKeyBoard", "—\n"
"-"))
        self.btn_add_.setText(_translate("SoftKeyBoard", "+\n"
"="))
        self.btn_backspace_.setText(_translate("SoftKeyBoard", "Backspace"))
        self.char_q_.setText(_translate("SoftKeyBoard", "q"))
        self.char_w_.setText(_translate("SoftKeyBoard", "w"))
        self.char_e_.setText(_translate("SoftKeyBoard", "e"))
        self.char_r_.setText(_translate("SoftKeyBoard", "r"))
        self.char_t_.setText(_translate("SoftKeyBoard", "t"))
        self.char_y_.setText(_translate("SoftKeyBoard", "y"))
        self.char_u_.setText(_translate("SoftKeyBoard", "u"))
        self.char_i_.setText(_translate("SoftKeyBoard", "i"))
        self.char_o_.setText(_translate("SoftKeyBoard", "o"))
        self.char_p_.setText(_translate("SoftKeyBoard", "p"))
        self.btn_left_bracket_.setText(_translate("SoftKeyBoard", "{\n"
"["))
        self.btn_right_bracket_.setText(_translate("SoftKeyBoard", "}\n"
"]"))
        self.btn_slash_.setText(_translate("SoftKeyBoard", "|\n"
"\\"))
        self.char_a_.setText(_translate("SoftKeyBoard", "a"))
        self.char_s_.setText(_translate("SoftKeyBoard", "s"))
        self.char_d_.setText(_translate("SoftKeyBoard", "d"))
        self.char_f_.setText(_translate("SoftKeyBoard", "f"))
        self.char_g_.setText(_translate("SoftKeyBoard", "g"))
        self.char_h_.setText(_translate("SoftKeyBoard", "h"))
        self.char_j_.setText(_translate("SoftKeyBoard", "j"))
        self.char_k_.setText(_translate("SoftKeyBoard", "k"))
        self.char_l_.setText(_translate("SoftKeyBoard", "l"))
        self.btn_semicolon_.setText(_translate("SoftKeyBoard", ":\n"
";"))
        self.btn_quota_.setText(_translate("SoftKeyBoard", "\"\n"
"\'"))
        self.btn_enter_.setText(_translate("SoftKeyBoard", "Enter"))
        self.char_z_.setText(_translate("SoftKeyBoard", "z"))
        self.char_x_.setText(_translate("SoftKeyBoard", "x"))
        self.char_c_.setText(_translate("SoftKeyBoard", "c"))
        self.char_v_.setText(_translate("SoftKeyBoard", "v"))
        self.char_b_.setText(_translate("SoftKeyBoard", "b"))
        self.char_n_.setText(_translate("SoftKeyBoard", "n"))
        self.char_m_.setText(_translate("SoftKeyBoard", "m"))
        self.btn_comma_.setText(_translate("SoftKeyBoard", "<\n"
","))
        self.btn_dot_.setText(_translate("SoftKeyBoard", ">\n"
"."))
        self.btn_backslash_.setText(_translate("SoftKeyBoard", "?\n"
"/"))
        self.btn_up_.setText(_translate("SoftKeyBoard", "↑"))
        self.btn_shift_.setText(_translate("SoftKeyBoard", "Shift"))
        self.btn_clear_.setText(_translate("SoftKeyBoard", "Clear"))
        self.btn_capslock_.setText(_translate("SoftKeyBoard", "CapsLock"))
        self.btn_left_.setText(_translate("SoftKeyBoard", "←"))
        self.btn_down_.setText(_translate("SoftKeyBoard", "↓"))
        self.btn_right_.setText(_translate("SoftKeyBoard", "→"))

